config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ivn_components
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  get 'hello_stimulus', to: 'site#hello_stimulus', as: :hello_stimulus if Rails.env.development?

  unless Rails.env.development?
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end

  resources :forms, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js_form
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  resources :touchpoints, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  namespace :api do
    namespace :v0 do
      resources :forms, only: %i[index show]
    end
    namespace :v1 do
      resources :organizations, only: [:index]
      resources :collections, only: [:index]
      resources :omb_cx_reporting_collections, only: [:index]
      resources :forms, only: %i[index show]
      resources :websites, only: [:index]
      resources :service_providers, only: [:index]
      resources :services, only: %i[index show]
      resources :personas, only: [:index]
      resources :goals, only: [:index]
      resources :objectives, only: [:index]
      resources :users, only: [:index]
      resources :digital_products, only: %i[index show]
      resources :digital_service_accounts, only: %i[index show]
    end
  end

  namespace :admin do
    resources :ivn_source_component_links
    resources :ivn_links
    resources :ivn_sources
    resources :ivn_components
      get '/reporting/', to: 'reporting#index', as: :reporting
    get '/reporting/hisps/hisps', to: 'reporting#hisps', as: :hisps
    get '/reporting/hisps/hisp_services', to: 'reporting#hisp_services', as: :hisp_services
    get '/reporting/hisps/hisp_service_cx_data_collections', to: 'reporting#hisp_service_cx_data_collections', as: :hisp_service_cx_data_collections
    get '/reporting/hisps/hisp_service_cx_data_collections_summary', to: 'reporting#hisp_service_cx_data_collections_summary', as: :hisp_service_cx_data_collections_summary
    get '/reporting/hisps/hisp_service_questions', to: 'reporting#hisp_service_questions', as: :hisp_service_questions

    get '/reporting/lifespan', to: 'reporting#lifespan', as: :lifespan
    get '/reporting/no_submissions', to: 'reporting#no_submissions', as: :no_submissions
    get '/reporting/service_surveys', to: 'reporting#service_surveys', as: :service_surveys
    get '/submissions/search', to: 'submissions#search', as: :search_submissions
    get '/submissions/a11_analysis', to: 'submissions#a11_analysis', as: :a11_analysis
    get '/submissions/a11_chart', to: 'submissions#a11_chart', as: :a11_chart
    get '/submissions/responses_per_day', to: 'submissions#responses_per_day', as: :responses_per_day
    get '/submissions/responses_by_status', to: 'submissions#responses_by_status', as: :responses_by_status
    get '/submissions/submissions_table', to: 'submissions#submissions_table', as: :submissions_table
    get '/submissions/performance_gov', to: 'submissions#performance_gov', as: :performance_gov

    get 'heartbeat', to: 'site#heartbeat', as: :heartbeat
    get 'a11', to: 'site#a11', as: :a11
    resources :offerings do
      member do
        post 'add_offering_persona', to: 'offerings#add_offering_persona', as: :add_offering_persona
        post 'remove_offering_persona', to: 'offerings#remove_offering_persona', as: :remove_offering_persona
      end
    end
    resources :service_providers do |*_args|
      collection do
        get 'quadrants', to: 'service_providers#quadrants', as: :quadrants
        get 'search', to: 'service_providers#search', as: :search
      end
      member do
        post 'add_tag', to: 'service_providers#add_tag', as: :add_tag
        post 'remove_tag', to: 'service_providers#remove_tag', as: :remove_tag
        post 'add_service_provider_manager', to: 'service_providers#add_service_provider_manager', as: :add_service_provider_manager
        post 'remove_service_provider_manager', to: 'service_providers#remove_service_provider_manager', as: :remove_service_provider_manager
      end
    end
    resources :services do
      collection do
        get 'catalog', to: 'services#catalog', as: :catalog
        get 'search', to: 'services#search', as: :search
        get 'export_csv', to: 'services#export_csv', as: :export_csv
      end
      member do
        get 'equity-assessment', to: 'services#equity_assessment', as: :equity_assessment
        get 'cx-reporting', to: 'services#omb_cx_reporting', as: :omb_cx_reporting
        post 'add_tag', to: 'services#add_tag', as: :add_tag
        post 'remove_tag', to: 'services#remove_tag', as: :remove_tag
        post 'add_channel', to: 'services#add_channel', as: :add_channel
        post 'remove_channel', to: 'services#remove_channel', as: :remove_channel

        post 'add_service_manager', to: 'services#add_service_manager', as: :add_service_manager
        post 'remove_service_manager', to: 'services#remove_service_manager', as: :remove_service_manager

        post 'submit', to: 'services#submit', as: :submit
        post 'approve', to: 'services#approve', as: :approve
        post 'verify', to: 'services#verify', as: :verify
        post 'archive', to: 'services#archive', as: :archive
        post 'reset', to: 'services#reset', as: :reset
        get 'versions', to: 'services#versions', as: :versions
        get 'versions_export', to: 'services#export_versions', as: :export_versions
      end

      resources :service_stages
    end

    resources :collections do
      collection do
        get 'export_csv', to: 'collections#export_csv', as: :export_csv
        get 'export_omb_cx_reporting_collections_csv', to: 'collections#export_omb_cx_reporting_collections_csv', as: :export_omb_cx_reporting_collections_csv
      end
      member do
        post 'copy', to: 'collections#copy', as: :copy
        post 'submit', to: 'collections#submit', as: :submit
        post 'publish', to: 'collections#publish', as: :publish
        get 'events', to: 'collections#events', as: :events
      end
    end
    resources :omb_cx_reporting_collections
    resources :cscrm_data_collections
    resources :goals do
      member do
        patch 'update_organization_id', to: 'goals#update_organization_id', as: :update_organization_id
        patch 'update_name', to: 'goals#update_name', as: :update_name
        patch 'update_statement', to: 'goals#update_statement', as: :update_statement
        patch 'update_description', to: 'goals#update_description', as: :update_description
        patch 'update_position', to: 'goals#update_position', as: :update_position
        patch 'update_tags', to: 'goals#update_tags', as: :update_tags
        patch 'update_users', to: 'goals#update_users', as: :update_users
        patch 'update_four_year_goal', to: 'goals#update_four_year_goal', as: :update_four_year_goal
        patch 'update_parent_id', to: 'goals#update_parent_id', as: :update_parent_id
        get 'targets', to: 'goals#goal_targets', as: :targets
        get 'goal_objectives', to: 'goals#goal_objectives', as: :goal_objectives
        post 'add_tag', to: 'goals#add_tag', as: :add_tag
        post 'remove_tag', to: 'goals#remove_tag', as: :remove_tag
        post 'add_organization', to: 'goals#add_organization', as: :add_organization
        post 'remove_organization', to: 'goals#remove_organization', as: :remove_organization
      end
      resources :goal_targets
      resources :objectives do
        member do
          post 'add_tag', to: 'objectives#add_tag', as: :add_tag
          post 'remove_tag', to: 'objectives#remove_tag', as: :remove_tag
        end
      end
    end
    resources :milestones
    resources :objectives

    resources :websites do
      collection do
        get :review, to: 'websites#review'
        get 'search', to: 'websites#search'
        get 'gsa', to: 'websites#gsa'
        get 'dendrogram', to: 'websites#dendrogram', as: :dendrogram
        get 'dendrogram_json', to: 'websites#dendrogram_json'
        get 'export_csv', to: 'websites#export_csv', as: :export_csv
        get 'collection_preview', to: 'websites@collection_preview', as: :collection_preview
      end
      member do
        get 'costs', to: 'websites#costs', as: :costs
        get 'statuscard', to: 'websites#statuscard', as: :statuscard
        get 'collection_request', to: 'websites@collection_request', as: :collection_request
        post 'approve', to: 'websites#approve', as: :approve
        post 'deny', to: 'websites#deny', as: :deny
        post 'develop', to: 'websites#develop', as: :develop
        post 'stage', to: 'websites#stage', as: :stage
        post 'launch', to: 'websites#launch', as: :launch
        post 'redirect', to: 'websites#redirect', as: :redirect
        post 'archive', to: 'websites#archive', as: :archive
        post 'decommission', to: 'websites#decommission', as: :decommission
        post 'reset', to: 'websites#reset', as: :reset
        get 'events', to: 'websites#events', as: :events
        post 'add_tag', to: 'websites#add_tag', as: :add_tag
        post 'remove_tag', to: 'websites#remove_tag', as: :remove_tag
        get 'versions', to: 'websites#versions', as: :versions
        get 'versions_export', to: 'websites#export_versions', as: :export_versions
        post 'add_website_manager', to: 'websites#add_website_manager', as: :add_website_manager
        post 'remove_website_manager', to: 'websites#remove_website_manager', as: :remove_website_manager

app/models/goal_target.rb
# frozen_string_literal: true

class GoalTarget < ApplicationRecord
  belongs_to :goal

  validates :assertion, presence: true
end

app/controllers/admin/goal_targets_controller.rb
# frozen_string_literal: true

module Admin
  class GoalTargetsController < AdminController
    before_action :set_goal
    before_action :set_goal_target, only: %i[show edit update destroy]

    def index
      @goal_targets = GoalTarget.all
    end

    def show; end

    def new
      @goal_target = GoalTarget.new
      @goal_target.assertion = 'New goal target'
      @goal_target.starting_value = 0
      @goal_target.target_value = 0
      @goal_target.current_value = 0
      render layout: false
    end

    def edit
      render layout: false
    end

    def create
      ensure_performance_manager_permissions

      @goal_target = GoalTarget.new(goal_target_params)

      respond_to do |format|
        if @goal_target.save
          format.html { redirect_to admin_goal_goal_target_path(@goal, @goal_target), notice: 'Goal target was successfully created.' }
          format.json { render :create, status: :created, goal: @goal }
        else
          format.html { render :new }
          format.json { render json: @goal_target.errors, status: :unprocessable_entity }
        end
        format.js
      end
    end

    def update
      ensure_performance_manager_permissions

      respond_to do |format|
        if @goal_target.update(goal_target_params)
          format.html { redirect_to admin_goal_goal_target_path(@goal, @goal_target), notice: 'Goal target was successfully updated.' }
          format.json { render :update, status: :updated, goal: @goal }
        else
          format.html { render :edit }
          format.json { render json: @goal_target.errors, status: :unprocessable_entity }
        end
        format.js
      end
    end

    def destroy
      ensure_performance_manager_permissions
      @goal_target.destroy

      respond_to do |format|
        format.html { redirect_to admin_goal_goal_targets_url(@goal), notice: 'Goal target was successfully destroyed.' }
        format.json { render :destroy, status: :deleted, goal: @goal }
        format.js
      end
    end

    private

    def set_goal
      @goal = Goal.find(params[:goal_id])
    end

    def set_goal_target
      @goal_target = GoalTarget.find(params[:id])
    end

    def goal_target_params
      params.require(:goal_target).permit(:goal_id, :target_date_at, :assertion, :kpi, :starting_value, :target_value, :current_value)
    end
  end
end

app/views/admin/goal_targets/_form.html.erb
<%= form_with(model: goal_target, url: goal_target.persisted? ? admin_goal_goal_target_path(@goal) : admin_goal_goal_targets_path(@goal),local: false) do |form| %>
  <% if goal_target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal_target.errors.count, "error") %> prohibited this goal_target from being saved:</h2>

      <ul>
        <% goal_target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :goal_id, value: @goal.id %>

  <div class="field">
    <%= form.label :target_date_at, class: "usa-label" %>
    <%= form.datetime_select :target_date_at, class: "usa-input" %>
  </div>

  <div class="field">
    <%= form.label :assertion, class: "usa-label" %>
    <%= form.text_area :assertion, class: "usa-textarea" %>
  </div>

  <div class="field">
    <%= form.label :kpi, class: "usa-label" %>
    <%= form.text_field :kpi, class: "usa-input" %>
  </div>

  <div class="field">
    <%= form.label :starting_value, class: "usa-label" %>
    <%= form.number_field :starting_value, class: "usa-input" %>
  </div>

  <div class="field">
    <%= form.label :target_value, class: "usa-label" %>
    <%= form.number_field :target_value, class: "usa-input" %>
  </div>

  <div class="field">
    <%= form.label :current_value, class: "usa-label" %>
    <%= form.number_field :current_value, class: "usa-input" %>
  </div>

  <p>
    <%= form.submit class: "usa-button update-goal-target" %>
  </p>
<% end %>

app/views/admin/goal_targets/create.js.erb
$(".goal-targets").html("<%= escape_javascript render(:partial => 'admin/goals/goal_targets', :locals => { :goal => @goal }) %>");

app/views/admin/goal_targets/destroy.js.erb
$(".goal-targets").html("<%= escape_javascript render(:partial => 'admin/goals/goal_targets', :locals => { :goal => @goal }) %>");

app/views/admin/goal_targets/edit.html.erb
<%= render 'form', goal_target: @goal_target %>

<%= link_to 'Cancel', admin_goal_path(@goal), class: "usa-button cancel-goal-target" %>

<script>
  $('.cancel-goal-target').on("click", function(event) {
    event.preventDefault();
    $.ajax({
      type: "GET",
      url: $(this).attr("href") + "/targets"
    });
  });
</script>

app/views/admin/goal_targets/index.html.erb
<% content_for :navigation_title do %>
  Goal Targets
<% end %>
<p>
  <%= link_to admin_goals_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Goals
  <% end %>
</p>

<table class="usa-table">
  <thead>
    <tr>
      <th>By...</th>
      <th>We will...</th>
      <th>KPI</th>
      <th>Starting value</th>
      <th>Target value</th>
      <th>Current value</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goal_targets.each do |goal_target| %>
      <tr>
        <td><%= goal_target.target_date_at %></td>
        <td><%= goal_target.assertion %></td>
        <td><%= goal_target.kpi %></td>
        <td><%= goal_target.starting_value %></td>
        <td><%= goal_target.target_value %></td>
        <td><%= goal_target.current_value %></td>
        <td><%= goal_target.goal %></td>
        <td><%= link_to 'Show', goal_target %></td>
        <td><%= link_to 'Edit', edit_goal_target_path(goal_target) %></td>
        <td><%= link_to 'Destroy', goal_target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to 'New Goal Target', new_admin_goal_goal_target_path(@goal), class: "usa-button" %>
</p>

app/views/admin/goal_targets/new.html.erb
<%= render 'form', goal_target: @goal_target %>

<%= link_to 'Cancel', admin_goal_path(@goal), class: "usa-button cancel-goal-target" %>

<script>
  $('.cancel-goal-target').on("click", function(event) {
    event.preventDefault();
    $.ajax({
      type: "GET",
      url: $(this).attr("href") + "/targets"
    });
  });
</script>

app/views/admin/goal_targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @goal_target.goal.name %>
</p>

<p>
  <strong>Target date at:</strong>
  <%= @goal_target.target_date_at %>
</p>

<p>
  <strong>Assertion:</strong>
  <%= @goal_target.assertion %>
</p>

<p>
  <strong>Kpi:</strong>
  <%= @goal_target.kpi %>
</p>

<p>
  <strong>Starting value:</strong>
  <%= @goal_target.starting_value %>
</p>

<p>
  <strong>Target value:</strong>
  <%= @goal_target.target_value %>
</p>

<p>
  <strong>Current value:</strong>
  <%= @goal_target.current_value %>
</p>

<%= link_to 'Edit', edit_admin_goal_goal_target_path(@goal, @goal_target) %> |
<%= link_to 'Back', admin_goal_goal_targets_path(@goal) %>

app/views/admin/goal_targets/update.js.erb
$(".goal-targets").html("<%= escape_javascript render(:partial => 'admin/goals/goal_targets', :locals => { :goal => @goal }) %>");