config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ivn_components
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  get 'hello_stimulus', to: 'site#hello_stimulus', as: :hello_stimulus if Rails.env.development?

  unless Rails.env.development?
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end

  resources :forms, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js_form
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  resources :touchpoints, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  namespace :api do
    namespace :v0 do
      resources :forms, only: %i[index show]
    end
    namespace :v1 do
      resources :organizations, only: [:index]
      resources :collections, only: [:index]
      resources :omb_cx_reporting_collections, only: [:index]
      resources :forms, only: %i[index show]
      resources :websites, only: [:index]
      resources :service_providers, only: [:index]
      resources :services, only: %i[index show]
      resources :personas, only: [:index]
      resources :goals, only: [:index]
      resources :objectives, only: [:index]
      resources :users, only: [:index]
      resources :digital_products, only: %i[index show]
      resources :digital_service_accounts, only: %i[index show]
    end
  end

  namespace :admin do
    resources :ivn_source_component_links
    resources :ivn_links
    resources :ivn_sources
    resources :ivn_components
      get '/reporting/', to: 'reporting#index', as: :reporting
    get '/reporting/hisps/hisps', to: 'reporting#hisps', as: :hisps
    get '/reporting/hisps/hisp_services', to: 'reporting#hisp_services', as: :hisp_services
    get '/reporting/hisps/hisp_service_cx_data_collections', to: 'reporting#hisp_service_cx_data_collections', as: :hisp_service_cx_data_collections
    get '/reporting/hisps/hisp_service_cx_data_collections_summary', to: 'reporting#hisp_service_cx_data_collections_summary', as: :hisp_service_cx_data_collections_summary
    get '/reporting/hisps/hisp_service_questions', to: 'reporting#hisp_service_questions', as: :hisp_service_questions

    get '/reporting/lifespan', to: 'reporting#lifespan', as: :lifespan
    get '/reporting/no_submissions', to: 'reporting#no_submissions', as: :no_submissions
    get '/reporting/service_surveys', to: 'reporting#service_surveys', as: :service_surveys
    get '/submissions/search', to: 'submissions#search', as: :search_submissions
    get '/submissions/a11_analysis', to: 'submissions#a11_analysis', as: :a11_analysis
    get '/submissions/a11_chart', to: 'submissions#a11_chart', as: :a11_chart
    get '/submissions/responses_per_day', to: 'submissions#responses_per_day', as: :responses_per_day
    get '/submissions/responses_by_status', to: 'submissions#responses_by_status', as: :responses_by_status
    get '/submissions/submissions_table', to: 'submissions#submissions_table', as: :submissions_table
    get '/submissions/performance_gov', to: 'submissions#performance_gov', as: :performance_gov

    get 'heartbeat', to: 'site#heartbeat', as: :heartbeat
    get 'a11', to: 'site#a11', as: :a11
    resources :offerings do
      member do
        post 'add_offering_persona', to: 'offerings#add_offering_persona', as: :add_offering_persona
        post 'remove_offering_persona', to: 'offerings#remove_offering_persona', as: :remove_offering_persona
      end
    end
    resources :service_providers do |*_args|
      collection do
        get 'quadrants', to: 'service_providers#quadrants', as: :quadrants
        get 'search', to: 'service_providers#search', as: :search
      end
      member do
        post 'add_tag', to: 'service_providers#add_tag', as: :add_tag
        post 'remove_tag', to: 'service_providers#remove_tag', as: :remove_tag
        post 'add_service_provider_manager', to: 'service_providers#add_service_provider_manager', as: :add_service_provider_manager
        post 'remove_service_provider_manager', to: 'service_providers#remove_service_provider_manager', as: :remove_service_provider_manager
      end
    end
    resources :services do
      collection do
        get 'catalog', to: 'services#catalog', as: :catalog
        get 'search', to: 'services#search', as: :search
        get 'export_csv', to: 'services#export_csv', as: :export_csv
      end
      member do
        get 'equity-assessment', to: 'services#equity_assessment', as: :equity_assessment
        get 'cx-reporting', to: 'services#omb_cx_reporting', as: :omb_cx_reporting
        post 'add_tag', to: 'services#add_tag', as: :add_tag
        post 'remove_tag', to: 'services#remove_tag', as: :remove_tag
        post 'add_channel', to: 'services#add_channel', as: :add_channel
        post 'remove_channel', to: 'services#remove_channel', as: :remove_channel

        post 'add_service_manager', to: 'services#add_service_manager', as: :add_service_manager
        post 'remove_service_manager', to: 'services#remove_service_manager', as: :remove_service_manager

        post 'submit', to: 'services#submit', as: :submit
        post 'approve', to: 'services#approve', as: :approve
        post 'verify', to: 'services#verify', as: :verify
        post 'archive', to: 'services#archive', as: :archive
        post 'reset', to: 'services#reset', as: :reset
        get 'versions', to: 'services#versions', as: :versions
        get 'versions_export', to: 'services#export_versions', as: :export_versions
      end

      resources :service_stages
    end

    resources :collections do
      collection do
        get 'export_csv', to: 'collections#export_csv', as: :export_csv
        get 'export_omb_cx_reporting_collections_csv', to: 'collections#export_omb_cx_reporting_collections_csv', as: :export_omb_cx_reporting_collections_csv
      end
      member do
        post 'copy', to: 'collections#copy', as: :copy
        post 'submit', to: 'collections#submit', as: :submit
        post 'publish', to: 'collections#publish', as: :publish
        get 'events', to: 'collections#events', as: :events
      end
    end
    resources :omb_cx_reporting_collections
    resources :cscrm_data_collections
    resources :goals do
      member do
        patch 'update_organization_id', to: 'goals#update_organization_id', as: :update_organization_id
        patch 'update_name', to: 'goals#update_name', as: :update_name
        patch 'update_statement', to: 'goals#update_statement', as: :update_statement
        patch 'update_description', to: 'goals#update_description', as: :update_description
        patch 'update_position', to: 'goals#update_position', as: :update_position
        patch 'update_tags', to: 'goals#update_tags', as: :update_tags
        patch 'update_users', to: 'goals#update_users', as: :update_users
        patch 'update_four_year_goal', to: 'goals#update_four_year_goal', as: :update_four_year_goal
        patch 'update_parent_id', to: 'goals#update_parent_id', as: :update_parent_id
        get 'targets', to: 'goals#goal_targets', as: :targets
        get 'goal_objectives', to: 'goals#goal_objectives', as: :goal_objectives
        post 'add_tag', to: 'goals#add_tag', as: :add_tag
        post 'remove_tag', to: 'goals#remove_tag', as: :remove_tag
        post 'add_organization', to: 'goals#add_organization', as: :add_organization
        post 'remove_organization', to: 'goals#remove_organization', as: :remove_organization
      end
      resources :goal_targets
      resources :objectives do
        member do
          post 'add_tag', to: 'objectives#add_tag', as: :add_tag
          post 'remove_tag', to: 'objectives#remove_tag', as: :remove_tag
        end
      end
    end
    resources :milestones
    resources :objectives

    resources :websites do
      collection do
        get :review, to: 'websites#review'
        get 'search', to: 'websites#search'
        get 'gsa', to: 'websites#gsa'
        get 'dendrogram', to: 'websites#dendrogram', as: :dendrogram
        get 'dendrogram_json', to: 'websites#dendrogram_json'
        get 'export_csv', to: 'websites#export_csv', as: :export_csv
        get 'collection_preview', to: 'websites@collection_preview', as: :collection_preview
      end
      member do
        get 'costs', to: 'websites#costs', as: :costs
        get 'statuscard', to: 'websites#statuscard', as: :statuscard
        get 'collection_request', to: 'websites@collection_request', as: :collection_request
        post 'approve', to: 'websites#approve', as: :approve
        post 'deny', to: 'websites#deny', as: :deny
        post 'develop', to: 'websites#develop', as: :develop
        post 'stage', to: 'websites#stage', as: :stage
        post 'launch', to: 'websites#launch', as: :launch
        post 'redirect', to: 'websites#redirect', as: :redirect
        post 'archive', to: 'websites#archive', as: :archive
        post 'decommission', to: 'websites#decommission', as: :decommission
        post 'reset', to: 'websites#reset', as: :reset
        get 'events', to: 'websites#events', as: :events
        post 'add_tag', to: 'websites#add_tag', as: :add_tag
        post 'remove_tag', to: 'websites#remove_tag', as: :remove_tag
        get 'versions', to: 'websites#versions', as: :versions
        get 'versions_export', to: 'websites#export_versions', as: :export_versions
        post 'add_website_manager', to: 'websites#add_website_manager', as: :add_website_manager
        post 'remove_website_manager', to: 'websites#remove_website_manager', as: :remove_website_manager

app/models/cscrm_data_collection.rb
# frozen_string_literal: true
require 'csv'

class CscrmDataCollection < ApplicationRecord
  belongs_to :organization

  validates :year, presence: true
  validates :quarter, presence: true

  def self.to_csv
    collections = CscrmDataCollection.order('year, quarter')

    example_attributes = CscrmDataCollection.new.attributes
    attributes = example_attributes.keys

    CSV.generate(headers: true) do |csv|
      csv << attributes

      collections.each do |collection|
        csv << attributes.map { |attr| collection.send(attr) }
      end
    end
  end

end

app/controllers/admin/cscrm_data_collections_controller.rb
# frozen_string_literal: true

module Admin
  class CscrmDataCollectionsController < AdminController
    before_action :set_cscrm_data_collection, only: %i[show edit update destroy]

    def index
      respond_to do |format|
        format.html {
          @cscrm_data_collections = CscrmDataCollection.all
        }
        format.csv {
          ensure_admin
          csv_content = CscrmDataCollection.to_csv
          send_data csv_content
        }
      end
    end

    def show; end

    def new
      @cscrm_data_collection = CscrmDataCollection.new
    end

    def edit; end

    def create
      @cscrm_data_collection = CscrmDataCollection.new(cscrm_data_collection_params)

      respond_to do |format|
        if @cscrm_data_collection.save
          format.html { redirect_to admin_cscrm_data_collection_url(@cscrm_data_collection), notice: 'Cscrm data collection was successfully created.' }
          format.json { render :show, status: :created, location: @cscrm_data_collection }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @cscrm_data_collection.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @cscrm_data_collection.update(cscrm_data_collection_params)
          format.html { redirect_to admin_cscrm_data_collection_url(@cscrm_data_collection), notice: 'Cscrm data collection was successfully updated.' }
          format.json { render :show, status: :ok, location: @cscrm_data_collection }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @cscrm_data_collection.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @cscrm_data_collection.destroy

      respond_to do |format|
        format.html { redirect_to cscrm_data_collections_url, notice: 'Cscrm data collection was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    def set_cscrm_data_collection
      @cscrm_data_collection = CscrmDataCollection.find(params[:id])
    end

    def cscrm_data_collection_params
      params.require(:cscrm_data_collection).permit(
        :user_id,
        :organization_id,
        :year,
        :quarter,
        :leadership_roles,
        :stakeholder_champion_identified,
        :pmo_established,
        :interdisciplinary_team_established,
        :enterprise_risk_management_function_established,
        :enterprise_wide_scrm_policy_established,
        :agency_wide_scrm_strategy_and_implementation_plan_established,
        :funding_for_initial_operating_capability,
        :staffing,
        :missions_identified_why_not,
        :prioritization_process,
        :established_process_information_sharing_with_fasc,
        :rating,
        roles_and_responsibilities: [],
        missions_identified: [],
        considerations_in_procurement_processes: [],
        conducts_scra_for_prioritized_products_and_services: [],
        personnel_required_to_complete_training: [],
        cybersecurity_supply_chain_risk_considerations: [],
      )
    end
  end
end

app/views/admin/cscrm_data_collections/_cscrm_data_collection.html.erb
<div id="<%= dom_id cscrm_data_collection %>">
  <p>
    <strong>Organization:</strong>
    <%= cscrm_data_collection.organization.name %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= cscrm_data_collection.year %>
  </p>

  <p>
    <strong>Quarter:</strong>
    <%= cscrm_data_collection.quarter %>
  </p>

  <p>
    <strong>Leadership roles:</strong>
    <%= cscrm_data_collection.leadership_roles %>
  </p>

  <p>
    <strong>Stakeholder champion identified:</strong>
    <%= cscrm_data_collection.stakeholder_champion_identified %>
  </p>

  <p>
    <strong>Pmo established:</strong>
    <%= cscrm_data_collection.pmo_established %>
  </p>

  <p>
    <strong>Interdisciplinary team established:</strong>
    <%= cscrm_data_collection.interdisciplinary_team_established %>
  </p>

  <p>
    <strong>Enterprise risk management function established:</strong>
    <%= cscrm_data_collection.enterprise_risk_management_function_established %>
  </p>

  <p>
    <strong>Enterprise wide scrm policy established:</strong>
    <%= cscrm_data_collection.enterprise_wide_scrm_policy_established %>
  </p>

  <p>
    <strong>Agency wide scrm strategy and implementation plan established:</strong>
    <%= cscrm_data_collection.agency_wide_scrm_strategy_and_implementation_plan_established %>
  </p>

  <p>
    <strong>Funding for initial operationg capability:</strong>
    <%= cscrm_data_collection.funding_for_initial_operating_capability %>
  </p>

  <p>
    <strong>Staffing:</strong>
    <%= cscrm_data_collection.staffing %>
  </p>

  <p>
    <strong>Roles and responsibilities:</strong>
    <%= cscrm_data_collection.roles_and_responsibilities %>
  </p>

  <p>
    <strong>Missions identified:</strong>
    <%= cscrm_data_collection.missions_identified %>
  </p>

  <p>
    <strong>Missions identified why not:</strong>
    <%= cscrm_data_collection.missions_identified_why_not %>
  </p>

  <p>
    <strong>Prioritization process:</strong>
    <%= cscrm_data_collection.prioritization_process %>
  </p>

  <p>
    <strong>Considerations in procurement processes:</strong>
    <%= cscrm_data_collection.considerations_in_procurement_processes %>
  </p>

  <p>
    <strong>Conducts scra for prioritized products and services:</strong>
    <%= cscrm_data_collection.conducts_scra_for_prioritized_products_and_services %>
  </p>

  <p>
    <strong>Personnel required to complete training:</strong>
    <%= cscrm_data_collection.personnel_required_to_complete_training %>
  </p>

  <p>
    <strong>Established process information sharing with fasc:</strong>
    <%= cscrm_data_collection.established_process_information_sharing_with_fasc %>
  </p>

  <p>
    <strong>Cybersecurity supply chain risk considerations incorporated into plans:</strong>
    <%= cscrm_data_collection.cybersecurity_supply_chain_risk_considerations %>
  </p>

</div>

app/views/admin/cscrm_data_collections/edit.html.erb
<% content_for :navigation_title do %>
  Editing CSCRM Data Collection
<% end %>

<p>
  <%= link_to admin_cscrm_data_collection_path(@cscrm_data_collection) do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to CSCRM Data Collection
  <% end %>
</p>

<div class="grid-row margin-bottom-3">
  <div class="desktop:grid-col-6">
  <%= render "form", cscrm_data_collection: @cscrm_data_collection %>

  <% if @cscrm_data_collection.persisted? %>
    <%= button_to "Destroy", admin_cscrm_data_collection_path(@cscrm_data_collection),
        class: "usa-button usa-button--secondary float-right",
        method: :delete %>
  <% end %>
  </div>
</div>

app/views/admin/cscrm_data_collections/index.html.erb
<% content_for :navigation_title do %>
  CSCRM Data Collections
  <%= link_to new_admin_cscrm_data_collection_path, class: "usa-button usa-button-inverted float-right" do %>
    <i class="fa fa-pencil-alt"></i>
    New Data Collection
  <% end %>
<% end %>

<div class="usa-summary-box margin-top-3" role="region" aria-labelledby="summary-box-key-information">
  <div class="usa-summary-box__body">
    <h3 class="usa-summary-box__heading" id="summary-box-key-information">
      Cybersecurity Supply Chain Risk Management (C-SCRM) Program Capability and Maturity: Self-Assessment
    </h3>
    <div class="usa-summary-box__text">
      <p>
        The Office of Management and Budget (OMB) requires all executive branch agencies to report on the status of their
        implementation of C-SCRM foundational elements and practices by completing and submitting this C-SCRM self-assessment,
        in accordance with statutory requirements noted below
      </p>

      <p>
        Pursuant to the Federal Acquisition Supply Chain Security Act of 2018, Title II of Strengthening and Enhancing
        Cyber-capabilities by Utilizing Risk Exposure (SECURE) Technology Act (P.L.115–390, December 21, 2018) (PUBL390.PS
        (congress.gov) executive branch agencies are responsible for assessing and managing their cybersecurity supply chain
        risks, consistent with NIST standards, guidelines, and practices. In addition, the statute requires agencies to report
        on C-SCRM progress and effectiveness.
      </p>

      <p>
        This initial reporting requirement is scoped and structured to limit the reporting burden while ensuring agencies
        provide information OMB needs to gain a baseline understanding of agencies’ current status in establishing a C-SCRM
        program capability. Information submitted will enable OMB to gain actionable insights into agency-specific and
        systemic
        challenges that may be hindering progress and inform the plans, actions, and decisions needed to resolve these
        challenges. Establishing and maturing a C-SCRM capability requires a transition away from a compliance-mindset and
        towards establishing, sustaining, and maturing an effective enterprise-wide C-SCRM capability that is sufficiently
        resourced, risk-based, and outcome-oriented.
      </p>

      <p>
        This integrated data collection (IDC) instruction provides the criteria, format, and mechanisms for Federal executive
        agencies to submit their bi-annual information collection submissions. The initial collection in February 2023, will
        serve as a baseline, upon which to expand in subsequent reporting cycles.
      </p>

      <p>
        To aid in the completion of their C-SCRM capability self-assessment, agencies should refer to FAQs maintained at
        [link].
      </p>

      <p>
        If there are additional agency questions, please submit to <a
          href="mailto:MBX.OMB.FASC@omb.eop.gov">MBX.OMB.FASC@omb.eop.gov</a>.
      </p>
    </div>
  </div>
</div>

<p>
  Direction:
  To determine the self-assessment responses for the measurement of foundational enterprise-wide C-SCRM capabilities,
  agencies shall:
</p>

<p>
  <ol class="usa-list">
    <li>
      Take steps to ensure responses submitted reflect an appropriate level of and span of internally coordinated input;
    </li>
    <li>
      Assess the status of their implementation and application of the foundational practices as described in National
      Institute of Standards and Technology SP 800-161 Rev. 1 Cybersecurity Supply Chain Risk Management for Systems and
      Organizations, May 2022 (SP 800-161 Rev. 1, C-SCRM Practices for Systems and Organizations | CSRC (nist.gov);
    </li>
    <li>
      Reference foundational practices and recommendations described in Information Technology: Federal Agencies Need to
      Take Urgent Action to Manage Supply Chain Risks, GAO-21-171, December 2020 (Information Technology: Federal Agencies
      Need to Take Urgent Action to Manage Supply Chain Risks | U.S. GAO); and
    </li>
    <li>
      Report self-assessment data semi-annually through GSA’s Touchpoints application, (HERE).
      OMB may change the vehicle for collecting this information, if changes are made, announcements will be communicated to
      the Agency C-SCRM Program Manager.
    </li>
  </ol>
</p>

<div id="cscrm_data_collections">
  <table class="usa-table collections">
    <thead>
      <tr>
        <th></th>
        <th data-sortable scope="col">Organization</th>
        <th data-sortable scope="col">Year</th>
        <th data-sortable scope="col">Quarter</th>
      </tr>
    </thead>

    <tbody>
      <% @cscrm_data_collections.each do |cscrm_data_collection| %>
      <tr>
        <td>
          <%= link_to "View" , admin_cscrm_data_collection_path(cscrm_data_collection) %>
        </td>
        <td>
          <%= cscrm_data_collection.organization.name %>
        </td>
        <td>
          <%= cscrm_data_collection.year %>
        </td>
        <td>
          <%= cscrm_data_collection.quarter %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/cscrm_data_collections/new.html.erb
<% content_for :navigation_title do %>
  CSCRM Data Collections
<% end %>

<p>
  <%= link_to admin_cscrm_data_collections_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to CSCRM Data Collections
  <% end %>
</p>

<div class="grid-row margin-bottom-3">
  <div class="desktop:grid-col-6">
    <div class="font-sans-lg">
      PART 1: REPORTING REQUIREMENTS
    </div>
    <p>
      Agencies are required to report on select C-SCRM benchmarks. This initial cycle will be used to baseline responses,
      gauge agencies’ C-SCRM implementation progress and to inform budgetary and programmatic requirements to build an
      effective C-SCRM capability. This IDC reflects the first iteration of reporting requirements in a multi-phased,
      multi-year effort to mature C-SCRM across executive branch agencies. Data will be collected semi-annually to monitor and
      assess progress as well as identify barriers and challenges.
    </p>
    <div class="font-sans-lg">
      ASSESSMENT
    </div>
    <p>
      This self-assessment is a living document and will be updated and revised as program capabilities and needs evolve,
      mature, and change. The assessment consists of benchmark factors for each of the six functions. The demonstrative
      statements were adapted from NIST guidance as well as
      <a href="https://www.gao.gov/products/gao-21-171" target="_blank" rel="noopener">GAO-21-171</a>.
    </p>

    <%= render "form", cscrm_data_collection: @cscrm_data_collection %>
  </div>
</div>

app/views/admin/cscrm_data_collections/show.html.erb
<% content_for :navigation_title do %>
  CSCRM Data Collection
  <%= link_to edit_admin_cscrm_data_collection_path(@cscrm_data_collection), class: "usa-button usa-button-inverted float-right" do %>
    <i class="fa fa-pencil-alt"></i>
    Edit
  <% end %>
<% end %>

<p>
  <%= link_to admin_cscrm_data_collections_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to CSCRM Data Collections
    <% end %>
</p>

<p style="color: green"><%= notice %></p>

<%= render @cscrm_data_collection %>