config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ivn_components
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  get 'hello_stimulus', to: 'site#hello_stimulus', as: :hello_stimulus if Rails.env.development?

  unless Rails.env.development?
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end

  resources :forms, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js_form
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  resources :touchpoints, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  namespace :api do
    namespace :v0 do
      resources :forms, only: %i[index show]
    end
    namespace :v1 do
      resources :organizations, only: [:index]
      resources :collections, only: [:index]
      resources :omb_cx_reporting_collections, only: [:index]
      resources :forms, only: %i[index show]
      resources :websites, only: [:index]
      resources :service_providers, only: [:index]
      resources :services, only: %i[index show]
      resources :personas, only: [:index]
      resources :goals, only: [:index]
      resources :objectives, only: [:index]
      resources :users, only: [:index]
      resources :digital_products, only: %i[index show]
      resources :digital_service_accounts, only: %i[index show]
    end
  end

  namespace :admin do
    resources :ivn_source_component_links
    resources :ivn_links
    resources :ivn_sources
    resources :ivn_components
      get '/reporting/', to: 'reporting#index', as: :reporting
    get '/reporting/hisps/hisps', to: 'reporting#hisps', as: :hisps
    get '/reporting/hisps/hisp_services', to: 'reporting#hisp_services', as: :hisp_services
    get '/reporting/hisps/hisp_service_cx_data_collections', to: 'reporting#hisp_service_cx_data_collections', as: :hisp_service_cx_data_collections
    get '/reporting/hisps/hisp_service_cx_data_collections_summary', to: 'reporting#hisp_service_cx_data_collections_summary', as: :hisp_service_cx_data_collections_summary
    get '/reporting/hisps/hisp_service_questions', to: 'reporting#hisp_service_questions', as: :hisp_service_questions

    get '/reporting/lifespan', to: 'reporting#lifespan', as: :lifespan
    get '/reporting/no_submissions', to: 'reporting#no_submissions', as: :no_submissions
    get '/reporting/service_surveys', to: 'reporting#service_surveys', as: :service_surveys
    get '/submissions/search', to: 'submissions#search', as: :search_submissions
    get '/submissions/a11_analysis', to: 'submissions#a11_analysis', as: :a11_analysis
    get '/submissions/a11_chart', to: 'submissions#a11_chart', as: :a11_chart
    get '/submissions/responses_per_day', to: 'submissions#responses_per_day', as: :responses_per_day
    get '/submissions/responses_by_status', to: 'submissions#responses_by_status', as: :responses_by_status
    get '/submissions/submissions_table', to: 'submissions#submissions_table', as: :submissions_table
    get '/submissions/performance_gov', to: 'submissions#performance_gov', as: :performance_gov

    get 'heartbeat', to: 'site#heartbeat', as: :heartbeat
    get 'a11', to: 'site#a11', as: :a11
    resources :offerings do
      member do
        post 'add_offering_persona', to: 'offerings#add_offering_persona', as: :add_offering_persona
        post 'remove_offering_persona', to: 'offerings#remove_offering_persona', as: :remove_offering_persona
      end
    end
    resources :service_providers do |*_args|
      collection do
        get 'quadrants', to: 'service_providers#quadrants', as: :quadrants
        get 'search', to: 'service_providers#search', as: :search
      end
      member do
        post 'add_tag', to: 'service_providers#add_tag', as: :add_tag
        post 'remove_tag', to: 'service_providers#remove_tag', as: :remove_tag
        post 'add_service_provider_manager', to: 'service_providers#add_service_provider_manager', as: :add_service_provider_manager
        post 'remove_service_provider_manager', to: 'service_providers#remove_service_provider_manager', as: :remove_service_provider_manager
      end
    end
    resources :services do
      collection do
        get 'catalog', to: 'services#catalog', as: :catalog
        get 'search', to: 'services#search', as: :search
        get 'export_csv', to: 'services#export_csv', as: :export_csv
      end
      member do
        get 'equity-assessment', to: 'services#equity_assessment', as: :equity_assessment
        get 'cx-reporting', to: 'services#omb_cx_reporting', as: :omb_cx_reporting
        post 'add_tag', to: 'services#add_tag', as: :add_tag
        post 'remove_tag', to: 'services#remove_tag', as: :remove_tag
        post 'add_channel', to: 'services#add_channel', as: :add_channel
        post 'remove_channel', to: 'services#remove_channel', as: :remove_channel

        post 'add_service_manager', to: 'services#add_service_manager', as: :add_service_manager
        post 'remove_service_manager', to: 'services#remove_service_manager', as: :remove_service_manager

        post 'submit', to: 'services#submit', as: :submit
        post 'approve', to: 'services#approve', as: :approve
        post 'verify', to: 'services#verify', as: :verify
        post 'archive', to: 'services#archive', as: :archive
        post 'reset', to: 'services#reset', as: :reset
        get 'versions', to: 'services#versions', as: :versions
        get 'versions_export', to: 'services#export_versions', as: :export_versions
      end

      resources :service_stages
    end

    resources :collections do
      collection do
        get 'export_csv', to: 'collections#export_csv', as: :export_csv
        get 'export_omb_cx_reporting_collections_csv', to: 'collections#export_omb_cx_reporting_collections_csv', as: :export_omb_cx_reporting_collections_csv
      end
      member do
        post 'copy', to: 'collections#copy', as: :copy
        post 'submit', to: 'collections#submit', as: :submit
        post 'publish', to: 'collections#publish', as: :publish
        get 'events', to: 'collections#events', as: :events
      end
    end
    resources :omb_cx_reporting_collections
    resources :cscrm_data_collections
    resources :goals do
      member do
        patch 'update_organization_id', to: 'goals#update_organization_id', as: :update_organization_id
        patch 'update_name', to: 'goals#update_name', as: :update_name
        patch 'update_statement', to: 'goals#update_statement', as: :update_statement
        patch 'update_description', to: 'goals#update_description', as: :update_description
        patch 'update_position', to: 'goals#update_position', as: :update_position
        patch 'update_tags', to: 'goals#update_tags', as: :update_tags
        patch 'update_users', to: 'goals#update_users', as: :update_users
        patch 'update_four_year_goal', to: 'goals#update_four_year_goal', as: :update_four_year_goal
        patch 'update_parent_id', to: 'goals#update_parent_id', as: :update_parent_id
        get 'targets', to: 'goals#goal_targets', as: :targets
        get 'goal_objectives', to: 'goals#goal_objectives', as: :goal_objectives
        post 'add_tag', to: 'goals#add_tag', as: :add_tag
        post 'remove_tag', to: 'goals#remove_tag', as: :remove_tag
        post 'add_organization', to: 'goals#add_organization', as: :add_organization
        post 'remove_organization', to: 'goals#remove_organization', as: :remove_organization
      end
      resources :goal_targets
      resources :objectives do
        member do
          post 'add_tag', to: 'objectives#add_tag', as: :add_tag
          post 'remove_tag', to: 'objectives#remove_tag', as: :remove_tag
        end
      end
    end
    resources :milestones
    resources :objectives

    resources :websites do
      collection do
        get :review, to: 'websites#review'
        get 'search', to: 'websites#search'
        get 'gsa', to: 'websites#gsa'
        get 'dendrogram', to: 'websites#dendrogram', as: :dendrogram
        get 'dendrogram_json', to: 'websites#dendrogram_json'
        get 'export_csv', to: 'websites#export_csv', as: :export_csv
        get 'collection_preview', to: 'websites@collection_preview', as: :collection_preview
      end
      member do
        get 'costs', to: 'websites#costs', as: :costs
        get 'statuscard', to: 'websites#statuscard', as: :statuscard
        get 'collection_request', to: 'websites@collection_request', as: :collection_request
        post 'approve', to: 'websites#approve', as: :approve
        post 'deny', to: 'websites#deny', as: :deny
        post 'develop', to: 'websites#develop', as: :develop
        post 'stage', to: 'websites#stage', as: :stage
        post 'launch', to: 'websites#launch', as: :launch
        post 'redirect', to: 'websites#redirect', as: :redirect
        post 'archive', to: 'websites#archive', as: :archive
        post 'decommission', to: 'websites#decommission', as: :decommission
        post 'reset', to: 'websites#reset', as: :reset
        get 'events', to: 'websites#events', as: :events
        post 'add_tag', to: 'websites#add_tag', as: :add_tag
        post 'remove_tag', to: 'websites#remove_tag', as: :remove_tag
        get 'versions', to: 'websites#versions', as: :versions
        get 'versions_export', to: 'websites#export_versions', as: :export_versions
        post 'add_website_manager', to: 'websites#add_website_manager', as: :add_website_manager
        post 'remove_website_manager', to: 'websites#remove_website_manager', as: :remove_website_manager

app/models/organization.rb
# frozen_string_literal: true

class Organization < ApplicationRecord
  acts_as_taggable_on :tags

  has_many :users
  has_many :service_providers
  has_many :services
  has_many :websites
  has_many :collections
  has_many :goals
  has_many :milestones, through: :goals
  has_many :objectives, through: :milestones
  has_many :forms

  mount_uploader :logo, LogoUploader

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :domain, presence: true
  validates :abbreviation, presence: true
  validates :abbreviation, uniqueness: true

  def slug
    abbreviation.downcase
  end

  def to_param
    slug
  end
end

app/controllers/admin/organizations_controller.rb
# frozen_string_literal: true

module Admin
  class OrganizationsController < AdminController
    before_action :set_organization, only: %i[
      show
      performance
      edit
      update
      performance_update
      destroy
      add_tag
      remove_tag
      create_two_year_goal
      create_four_year_goal
      delete_two_year_goal
      delete_four_year_goal
      sort_goals
      sort_objectives
    ]

    def index
      @organizations = Organization.all.order(:name)
      @tags = Organization.tag_counts_by_name
    end

    def show
      @forms = @organization.forms
      @collections = @organization.collections
      @users = @organization.users.active.order(:email)
    end

    def new
      ensure_admin

      @organization = Organization.new
    end

    def edit
      ensure_admin
    end

    def performance
      ensure_performance_manager_permissions
    end

    def create
      ensure_admin

      @organization = Organization.new(organization_params)

      respond_to do |format|
        if @organization.save
          Event.log_event(Event.names[:organization_created], 'Organization', @organization.id, "Organization #{@organization.name} created at #{DateTime.now}", current_user.id)
          format.html { redirect_to admin_organization_path(@organization), notice: 'Organization was successfully created.' }
          format.json { render :show, status: :created, location: @organization }
        else
          format.html { render :new }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
    end

    def create_four_year_goal
      ensure_performance_manager_permissions

      @goal = Goal.new
      @goal.organization_id = @organization.id
      @goal.four_year_goal = true
      @goal.name = 'New Strategic Goal'
      @goal.save
    end

    def create_two_year_goal
      ensure_performance_manager_permissions

      @goal = Goal.new
      @goal.organization_id = @organization.id
      @goal.four_year_goal = false
      @goal.name = 'New 2 Year APG'
      @goal.save
    end

    def sort_goals
      ensure_performance_manager_permissions

      params[:goal].each_with_index do |id, index|
        Goal.where(id:).update_all(position: index + 1)
      end

      head :ok
    end

    def sort_objectives
      ensure_performance_manager_permissions

      params[:objective].each_with_index do |id, index|
        Objective.where(id:).update_all(position: index + 1)
      end

      head :ok
    end

    def delete_two_year_goal
      ensure_performance_manager_permissions

      Goal.find(params[:goal_id]).destroy
    end

    def delete_four_year_goal
      ensure_performance_manager_permissions

      Goal.find(params[:goal_id]).destroy
    end

    def update
      ensure_admin

      respond_to do |format|
        if @organization.update(organization_params)
          Event.log_event(Event.names[:organization_updated], 'Organization', @organization.id, "Organization #{@organization.name} updated at #{DateTime.now}", current_user.id)
          format.html { redirect_to admin_organization_path(@organization), notice: 'Organization was successfully updated.' }
          format.json { render :show, status: :ok, location: @organization }
        else
          format.html { render :edit }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
    end

    def performance_update
      ensure_performance_manager_permissions

      respond_to do |format|
        if @organization.update(organization_params)
          format.html { redirect_to performance_admin_organization_path(@organization), notice: 'Organization was successfully updated.' }
          format.json { render :show, status: :ok, location: @organization }
        else
          format.html { render :edit }
          format.json { render json: @organization.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      ensure_admin

      @organization.destroy
      Event.log_event(Event.names[:organization_deleted], 'Organization', @organization.id, "Organization #{@organization.name} deleted at #{DateTime.now}", current_user.id)

      respond_to do |format|
        format.html { redirect_to admin_organizations_url, notice: 'Organization was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    def search
      search_text = params[:search]
      tag_name = params[:tag]
      if search_text.present?
        search_text = "%#{search_text}%"
        @organizations = Organization.where(' domain ilike ? or name ilike ? or abbreviation ilike ? or url ilike ?  ', search_text, search_text, search_text, search_text)
      elsif tag_name.present?
        @organizations = Organization.tagged_with(tag_name)
      else
        @organizations = Organization.all
      end
    end

    def add_tag
      ensure_admin

      @organization.tag_list.add(organization_params[:tag_list].split(','))
      @organization.save
    end

    def remove_tag
      ensure_admin

      @organization.tag_list.remove(organization_params[:tag_list].split(','))
      @organization.save
    end

    private

    def set_organization
      @organization = Organization.find_by_id(params[:id]) || Organization.find_by_abbreviation(params[:id].upcase)
    end

    def organization_params
      params.require(:organization).permit(
        :name,
        :domain,
        :logo,
        :url,
        :abbreviation,
        :notes,
        :external_id,
        :enable_ip_address,
        :digital_analytics_path,
        :mission_statement,
        :mission_statement_url,
        :tag_list,
        :performance_url,
        :strategic_plan_url,
        :learning_agenda_url,
      )
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class OrganizationsController < ::ApiController
      def index
        respond_to do |format|
          format.json do
            render json: Organization.all.order(:id), each_serializer: OrganizationSerializer
          end
        end
      end
    end
  end
end

app/views/admin/organizations/_results.html.erb
<table class="usa-table" style="width: 100%;">
  <thead>
    <tr>
      <th data-sortable scope="col">Abbreviation</th>
      <th data-sortable scope="col">Name</th>
      <th data-sortable scope="col">URL</th>
      <th data-sortable scope="col">Users</th>
      <th data-sortable scope="col">Forms</th>
      <th data-sortable scope="col">Services</th>
      <th data-sortable scope="col">Websites</th>
      <th data-sortable scope="col">Collections</th>
      <th data-sortable scope="col">Tags</th>
    </tr>
  </thead>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.abbreviation %></td>
        <td><%= link_to organization.name, admin_organization_path(organization) %></td>
        <td>
          <%= link_to organization.url, organization.url, target: "_blank", rel: "noopener" %>
        </td>
        <td>
          <%= organization.users.count %>
        </td>
        <td>
          <%= organization.forms.count %>
        </td>
        <td>
          <%= organization.services.count %>
        </td>
        <td>
          <%= organization.websites.count %>
        </td>
        <td>
          <%= organization.collections.count %>
        </td>
        <td>
          <%= organization.tag_list %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/organizations/_two_year_goals.html.erb
<h4>
  Annual Performance Goals (APG) (2-year)
</h4>
<div class="sorting-div-2">
  <% @organization.goals.includes(:organization).annual_performance_goals.order(:position).each_with_index do |goal, i| %>
    <div class="well" id="<%= dom_id(goal) %>" data-id="<%= goal.id %>" data-url="<%= sort_goals_admin_organization_path(goal.organization) %>">
      <div class="delete-float-right">
        <%= link_to delete_two_year_goal_admin_organization_path(@organization) + "?goal_id=#{goal.id}", method: :delete, data: { confirm: 'Are you sure?' }, :remote => true do %>
            <i class="fa fa-trash" title="Delete goal"></i>
        <% end %>
      </div>
      <div class="font-sans-lg">
        <%= i + 1 %>.
        <%= link_to goal.name, admin_goal_path(goal) %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "Create 2-year APG", create_two_year_goal_admin_organization_path(@organization), class: "usa-button", remote: true %>
<script>
  $(".sorting-div-2").sortable({
    distance: 20,
    update: function(e, ui) {
      var url = ui.item.data("url");
      $.ajax({
        url: url,
        type: "PATCH",
        data: $(this).sortable('serialize')
      });
    }
  });
</script>

app/views/admin/organizations/index.html.erb
<% content_for :navigation_title do %>
  Organizations
  <%= link_to new_admin_organization_path, class: "usa-button usa-button-inverted float-right" do %>
  <i class="fa fa-plus-circle"></i>
    New Organization
  <% end %>
<% end %>

<div class="well">
  <div class="field">
    <%= label_tag :search_text, "Search by name, domain, abbreviation or url" %>
    <%= text_field_tag :search_text, nil, class: "usa-input", autofocus: true %>
    <% if @tags.first %>
      <p>
        Search by tag
      </p>
      <div class="tag-list">
        <% @tags.order(:name).each do | tag | %>
          <a href="#" class="search-tag-link" data-name="<%= tag.name %>">
            <span class="usa-tag">
              <%= tag.name %> (<%= tag.taggings_count %>)
            </span>
          </a>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="search-results">
  <%= render 'results' %>
</div>

<script>
  $(function() {
    $("#search_text").keyup(debounce(function() {
      var searchValue = $("#search_text").val();

      $.ajax({
        url: '/admin/organizations/search',
        data: {
          search: searchValue
        }
      });
    }, 400));

    $(".search-tag-link").on("click", function() {
      $("#search_text").val("");

      $.ajax({
        url: '/admin/organizations/search',
        data: {
          tag: $(this).attr("data-name")
        }
      });

    });
  });
</script>

app/views/admin/organizations/new.html.erb
<% content_for :navigation_title do %>
  New Organization
<% end %>
<p>
  <%= link_to admin_organizations_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Organizations
  <% end %>
</p>

<%= render 'form', organization: @organization %>

app/views/admin/organizations/performance.html.erb
<% content_for :navigation_title do %>
  Performance management
  <%= link_to performance_edit_admin_organization_path(@organization), class: "usa-button usa-button-inverted float-right" do %>
    <i class="fa fa-pencil-alt"></i>
    Edit
  <% end %>
<% end %>

<p>
  <%= link_to admin_performance_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Performance
  <% end %>
</p>

<div>
  <h2>
    <%= @organization.name %>
  </h2>
  <div class="grid-row">
    <div class="grid-col-12 usa-prose">
      <p>
        <strong>
          <%= @organization.abbreviation %>
        </strong>
      </p>
      <p>
        <%= @organization.mission_statement %>
      </p>

      <hr>

      <div class="grid-row font-sans-lg">
        <div class="grid-col-12">
          <p>
            Strategic plan
            &nbsp;
            <%= link_to "PDF", @organization.strategic_plan_url, class: "font-sans-xs" %>
            &nbsp;
            <i class="fa fa-external-link-alt font-sans-xs"></i>
          </p>
          <p>
            Performance plan (next year)
            &nbsp;
            <%= link_to "PDF", @organization.performance_url, class: "font-sans-xs" %>
            &nbsp;
            <i class="fa fa-external-link-alt font-sans-xs"></i>
          </p>
          <p>
            Learning agenda
            &nbsp;
            <%= link_to "Link to evaluation.gov", @organization.learning_agenda_url, class: "font-sans-xs" %>
            &nbsp;
            <i class="fa fa-external-link-alt font-sans-xs"></i>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>
<section class="four-year-goals">
  <%= render partial: 'admin/organizations/four_year_goals', locals: { organization: @organization } %>
</section>
<br>
<hr>
<section class="two-year-goals">
  <%= render partial: 'admin/organizations/two_year_goals', locals: { organization: @organization } %>
</section>
<br>
<br>

app/views/admin/organizations/show.html.erb
<% content_for :navigation_title do %>
  Viewing Organization
  <%= link_to edit_admin_organization_path(@organization), class: "usa-button usa-button-inverted float-right" do %>
    <i class="fa fa-pencil-alt"></i>
    Edit
  <% end %>
<% end %>

<p>
  <%= link_to admin_organizations_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Organizations
  <% end %>
</p>

<div class="grid-row">
  <div class="grid-col-8">
    <div>
      <div class="grid-row">
        <div class="grid-col-12">
          <%= label_tag "Name", nil, class: "usa-label" %>
          <%= @organization.name %>
        </div>
        <div class="grid-col-12">
          <%= label_tag "Abbreviation", nil, class: "usa-label" %>
          <%= @organization.abbreviation %>
        </div>
        <div class="grid-col-12">
          <div>
            <%= label_tag "Organization Domain", nil, class: "usa-label" %>
            <small>
              used for the Allowlist of users email addresses
            </small>
            <br>
            <br>
            <%= @organization.domain %>
          </div>
        </div>
        <div class="grid-col-12">
          <%= label_tag "Website URL", nil, class: "usa-label" %>
          <br>
          <%= link_to(@organization.url, @organization.url, target: "_blank", rel: "noopener") %>
        </div>
      </div>


      <div class="usa-prose">
        <%= label_tag "Mission statement", nil, class: "usa-label" %>
        <br>
        <% if @organization.mission_statement.present? %>
          <%= @organization.mission_statement %>
        <% else %>
        <div class="usa-alert usa-alert--info">
          <div class="usa-alert__body">
            <p class="usa-alert__text">
              Mission statement has not been entered
            </p>
          </div>
        </div>
        <% end %>
      </div>
      <% if @organization.logo %>
      <p>
        <%= label_tag "Logo", nil, class: "usa-label" %>
        <br>
        <% if @organization.logo_url.present? %>
        (displaying Thumbnail version)
        <br>
        <br>
        <%= image_tag(@organization.logo.thumb.url) %>
        <br>
        <%= link_to "Full Size", @organization.logo.url, target: "_blank", rel: "noopener" %><br>
        <%= link_to "Thumbnail Size", @organization.logo.thumb.url, target: "_blank", rel: "noopener" %><br>
        <%= link_to "Card Size", @organization.logo.card.url, target: "_blank", rel: "noopener" %><br>
        <% else %>
          A logo has not yet been uploaded
        <% end %>
      </p>
      <% end %>
      <p>
        <%= label_tag "Digital Analytics URL", nil, class: "usa-label" %>
        <% if @organization.digital_analytics_path? %>
          <%= link_to("https://analytics.usa.gov/#{@organization.digital_analytics_path}", "https://analytics.usa.gov/#{@organization.digital_analytics_path}", target: "_blank", rel: "noopener") %>
          <% else %>
          <div class="usa-alert usa-alert--info">
            <div class="usa-alert__body">
              <p class="usa-alert__text">
                DAP path has not been entered
              </p>
            </div>
          </div>
          <% end %>
      </p>
      <p>
        <%= label_tag "Notes", nil, class: "usa-label" %>
        <% if @organization.notes.present? %>
          <%= @organization.notes %>
        <% else %>
        <div class="usa-alert usa-alert--info">
          <div class="usa-alert__body">
            <p class="usa-alert__text">
              Notes have not been entered
            </p>
          </div>
        </div>
        <% end %>
      </p>
    </div>

    <% if admin_permissions? || current_user.organization == @organization %>
    <div class="service-providers well">
      <h3>
        <%= pluralize(@organization.service_providers.size, "Service Providers") %>
      </h3>

      <% if @organization.service_providers.present? %>
      <ul class="usa-list">
      <% @organization.service_providers.order(:name).each do |service_provider| %>
        <li>
          <%= link_to service_provider.name, admin_service_provider_path(service_provider) %>
        </li>
      <% end %>
      </ul>
      <% else %>
      <div class="usa-alert usa-alert--info">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            No Service Providers at this time
          </p>
        </div>
      </div>
      <% end %>
    </div>
    <div class="service-providers well">
      <h3>
        <%= pluralize(@organization.services.size, "Service") %>
      </h3>

      <% if @organization.services.present? %>
      <ul class="usa-list">
      <% @organization.services.order(:name).each do |service| %>
        <li>
          <%= link_to service.name, admin_service_path(service) %>
          <% if service.service_provider %>
            - provided by
            <%= link_to service.service_provider.name, admin_service_path(service) %>
          <% end %>
        </li>
      <% end %>
      </ul>
      <% else %>
      <div class="usa-alert usa-alert--info">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            No Service Providers at this time
          </p>
        </div>
      </div>
      <% end %>
    </div>
    <div class="touchpoints well">
      <h3>
        <%= @forms.size %> Forms
      </h3>

      <% if @forms.present? %>
      <ul class="usa-list">
      <% @forms.each do |form| %>
        <li>
          <%= link_to form.name, admin_form_path(form) %>
        </li>
      <% end %>
      </ul>
      <% else %>
      <div class="usa-alert usa-alert--info">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            No Forms at this time
          </p>
        </div>
      </div>
      <% end %>

    </div>
    <div class="collections well">
      <h3>
        <%= @collections.size %> Collections
      </h3>

      <% if @collections.present? %>
        <ul class="usa-list">
        <% @collections.order(:year, :quarter).each do |collection| %>
          <li>
            <%= collection.year %>
            Q<%= collection.quarter %>
            &middot;
            <%= link_to collection.name, admin_collection_path(collection) %><br>
          </li>
        <% end %>
        </ul>
      <% else %>
      <div class="usa-alert usa-alert--info">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            No Collections at this time
          </p>
        </div>
      </div>
      <% end %>
      <h3>

    </div>
    <div class="users well">
      <h3>
        <%= @users.size %> Users
      </h3>

      <% if @users.present? %>
      <ul class="usa-list">
      <% @users.order(:email).each do |user| %>
        <li>
          <%= link_to user.email, admin_user_path(user) %>
        </li>
      <% end %>
      </ul>
      <% else %>
      <div class="usa-alert usa-alert--info">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            No Users at this time
          </p>
        </div>
      </div>
      <% end %>

    </div>
    <% end %>

  </div>
  <div class="grid-col-4">

  </div>
</div>