config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :ivn_components
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/admin/sidekiq'
  end

  get 'hello_stimulus', to: 'site#hello_stimulus', as: :hello_stimulus if Rails.env.development?

  unless Rails.env.development?
    match '/404', to: 'errors#not_found', via: :all
    match '/500', to: 'errors#internal_server_error', via: :all
  end

  resources :forms, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js_form
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  resources :touchpoints, only: [:show] do
    member do
      get 'js', to: 'touchpoints#js', as: :js
      get 'submit', to: 'submissions#new', form: true, as: :submit
    end
    resources :submissions, only: %i[new create]
  end

  namespace :api do
    namespace :v0 do
      resources :forms, only: %i[index show]
    end
    namespace :v1 do
      resources :organizations, only: [:index]
      resources :collections, only: [:index]
      resources :omb_cx_reporting_collections, only: [:index]
      resources :forms, only: %i[index show]
      resources :websites, only: [:index]
      resources :service_providers, only: [:index]
      resources :services, only: %i[index show]
      resources :personas, only: [:index]
      resources :goals, only: [:index]
      resources :objectives, only: [:index]
      resources :users, only: [:index]
      resources :digital_products, only: %i[index show]
      resources :digital_service_accounts, only: %i[index show]
    end
  end

  namespace :admin do
    resources :ivn_source_component_links
    resources :ivn_links
    resources :ivn_sources
    resources :ivn_components
      get '/reporting/', to: 'reporting#index', as: :reporting
    get '/reporting/hisps/hisps', to: 'reporting#hisps', as: :hisps
    get '/reporting/hisps/hisp_services', to: 'reporting#hisp_services', as: :hisp_services
    get '/reporting/hisps/hisp_service_cx_data_collections', to: 'reporting#hisp_service_cx_data_collections', as: :hisp_service_cx_data_collections
    get '/reporting/hisps/hisp_service_cx_data_collections_summary', to: 'reporting#hisp_service_cx_data_collections_summary', as: :hisp_service_cx_data_collections_summary
    get '/reporting/hisps/hisp_service_questions', to: 'reporting#hisp_service_questions', as: :hisp_service_questions

    get '/reporting/lifespan', to: 'reporting#lifespan', as: :lifespan
    get '/reporting/no_submissions', to: 'reporting#no_submissions', as: :no_submissions
    get '/reporting/service_surveys', to: 'reporting#service_surveys', as: :service_surveys
    get '/submissions/search', to: 'submissions#search', as: :search_submissions
    get '/submissions/a11_analysis', to: 'submissions#a11_analysis', as: :a11_analysis
    get '/submissions/a11_chart', to: 'submissions#a11_chart', as: :a11_chart
    get '/submissions/responses_per_day', to: 'submissions#responses_per_day', as: :responses_per_day
    get '/submissions/responses_by_status', to: 'submissions#responses_by_status', as: :responses_by_status
    get '/submissions/submissions_table', to: 'submissions#submissions_table', as: :submissions_table
    get '/submissions/performance_gov', to: 'submissions#performance_gov', as: :performance_gov

    get 'heartbeat', to: 'site#heartbeat', as: :heartbeat
    get 'a11', to: 'site#a11', as: :a11
    resources :offerings do
      member do
        post 'add_offering_persona', to: 'offerings#add_offering_persona', as: :add_offering_persona
        post 'remove_offering_persona', to: 'offerings#remove_offering_persona', as: :remove_offering_persona
      end
    end
    resources :service_providers do |*_args|
      collection do
        get 'quadrants', to: 'service_providers#quadrants', as: :quadrants
        get 'search', to: 'service_providers#search', as: :search
      end
      member do
        post 'add_tag', to: 'service_providers#add_tag', as: :add_tag
        post 'remove_tag', to: 'service_providers#remove_tag', as: :remove_tag
        post 'add_service_provider_manager', to: 'service_providers#add_service_provider_manager', as: :add_service_provider_manager
        post 'remove_service_provider_manager', to: 'service_providers#remove_service_provider_manager', as: :remove_service_provider_manager
      end
    end
    resources :services do
      collection do
        get 'catalog', to: 'services#catalog', as: :catalog
        get 'search', to: 'services#search', as: :search
        get 'export_csv', to: 'services#export_csv', as: :export_csv
      end
      member do
        get 'equity-assessment', to: 'services#equity_assessment', as: :equity_assessment
        get 'cx-reporting', to: 'services#omb_cx_reporting', as: :omb_cx_reporting
        post 'add_tag', to: 'services#add_tag', as: :add_tag
        post 'remove_tag', to: 'services#remove_tag', as: :remove_tag
        post 'add_channel', to: 'services#add_channel', as: :add_channel
        post 'remove_channel', to: 'services#remove_channel', as: :remove_channel

        post 'add_service_manager', to: 'services#add_service_manager', as: :add_service_manager
        post 'remove_service_manager', to: 'services#remove_service_manager', as: :remove_service_manager

        post 'submit', to: 'services#submit', as: :submit
        post 'approve', to: 'services#approve', as: :approve
        post 'verify', to: 'services#verify', as: :verify
        post 'archive', to: 'services#archive', as: :archive
        post 'reset', to: 'services#reset', as: :reset
        get 'versions', to: 'services#versions', as: :versions
        get 'versions_export', to: 'services#export_versions', as: :export_versions
      end

      resources :service_stages
    end

    resources :collections do
      collection do
        get 'export_csv', to: 'collections#export_csv', as: :export_csv
        get 'export_omb_cx_reporting_collections_csv', to: 'collections#export_omb_cx_reporting_collections_csv', as: :export_omb_cx_reporting_collections_csv
      end
      member do
        post 'copy', to: 'collections#copy', as: :copy
        post 'submit', to: 'collections#submit', as: :submit
        post 'publish', to: 'collections#publish', as: :publish
        get 'events', to: 'collections#events', as: :events
      end
    end
    resources :omb_cx_reporting_collections
    resources :cscrm_data_collections
    resources :goals do
      member do
        patch 'update_organization_id', to: 'goals#update_organization_id', as: :update_organization_id
        patch 'update_name', to: 'goals#update_name', as: :update_name
        patch 'update_statement', to: 'goals#update_statement', as: :update_statement
        patch 'update_description', to: 'goals#update_description', as: :update_description
        patch 'update_position', to: 'goals#update_position', as: :update_position
        patch 'update_tags', to: 'goals#update_tags', as: :update_tags
        patch 'update_users', to: 'goals#update_users', as: :update_users
        patch 'update_four_year_goal', to: 'goals#update_four_year_goal', as: :update_four_year_goal
        patch 'update_parent_id', to: 'goals#update_parent_id', as: :update_parent_id
        get 'targets', to: 'goals#goal_targets', as: :targets
        get 'goal_objectives', to: 'goals#goal_objectives', as: :goal_objectives
        post 'add_tag', to: 'goals#add_tag', as: :add_tag
        post 'remove_tag', to: 'goals#remove_tag', as: :remove_tag
        post 'add_organization', to: 'goals#add_organization', as: :add_organization
        post 'remove_organization', to: 'goals#remove_organization', as: :remove_organization
      end
      resources :goal_targets
      resources :objectives do
        member do
          post 'add_tag', to: 'objectives#add_tag', as: :add_tag
          post 'remove_tag', to: 'objectives#remove_tag', as: :remove_tag
        end
      end
    end
    resources :milestones
    resources :objectives

    resources :websites do
      collection do
        get :review, to: 'websites#review'
        get 'search', to: 'websites#search'
        get 'gsa', to: 'websites#gsa'
        get 'dendrogram', to: 'websites#dendrogram', as: :dendrogram
        get 'dendrogram_json', to: 'websites#dendrogram_json'
        get 'export_csv', to: 'websites#export_csv', as: :export_csv
        get 'collection_preview', to: 'websites@collection_preview', as: :collection_preview
      end
      member do
        get 'costs', to: 'websites#costs', as: :costs
        get 'statuscard', to: 'websites#statuscard', as: :statuscard
        get 'collection_request', to: 'websites@collection_request', as: :collection_request
        post 'approve', to: 'websites#approve', as: :approve
        post 'deny', to: 'websites#deny', as: :deny
        post 'develop', to: 'websites#develop', as: :develop
        post 'stage', to: 'websites#stage', as: :stage
        post 'launch', to: 'websites#launch', as: :launch
        post 'redirect', to: 'websites#redirect', as: :redirect
        post 'archive', to: 'websites#archive', as: :archive
        post 'decommission', to: 'websites#decommission', as: :decommission
        post 'reset', to: 'websites#reset', as: :reset
        get 'events', to: 'websites#events', as: :events
        post 'add_tag', to: 'websites#add_tag', as: :add_tag
        post 'remove_tag', to: 'websites#remove_tag', as: :remove_tag
        get 'versions', to: 'websites#versions', as: :versions
        get 'versions_export', to: 'websites#export_versions', as: :export_versions
        post 'add_website_manager', to: 'websites#add_website_manager', as: :add_website_manager
        post 'remove_website_manager', to: 'websites#remove_website_manager', as: :remove_website_manager

app/controllers/admin/collections_controller.rb
# frozen_string_literal: true

module Admin
  class CollectionsController < AdminController
    before_action :set_collection, only: %i[show edit copy
      submit publish
      update destroy
      events]

    def index
      @quarter = params[:quarter].present? ? params[:quarter].to_i : nil
      @year = params[:year].present? ? params[:year].to_i : nil

      if performance_manager_permissions?
        if @quarter && @year
          @collections = Collection.where(quarter: @quarter, year: @year)
            .order('organizations.name', :year, :quarter, 'service_providers.name')
            .includes(:organization, :service_provider)
        elsif @quarter
          @collections = Collection.where(quarter: @quarter)
            .order('organizations.name', :year, :quarter, 'service_providers.name')
            .includes(:organization, :service_provider)
        else
          @collections = Collection.all
            .order('organizations.name', :year, :quarter, 'service_providers.name')
            .includes(:organization, :service_provider)
        end
      elsif @quarter && @year
        @collections = current_user.collections.where(quarter: @quarter, year: @year)
            .order('organizations.name', :year, :quarter, 'service_providers.name')
            .includes(:organization, :service_provider)
      elsif @quarter
        @collections = current_user.collections.where(quarter: @quarter)
          .order('organizations.name', :year, :quarter, 'service_providers.name')
          .includes(:organization, :service_provider)
      else
        @collections = current_user.collections
          .order('organizations.name', :year, :quarter, 'service_providers.name')
          .includes(:organization, :service_provider)
      end
    end

    def show
      ensure_collection_owner(collection: @collection)
    end

    def new
      @collection = Collection.new
      @collection.user = current_user
      @collection.organization_id = params[:organization_id]
      @collection.service_provider_id = params[:service_provider_id]
      @collection.year = fiscal_year(Date.today)
      @collection.quarter = fiscal_quarter(Date.today)
    end

    def edit
      ensure_collection_owner(collection: @collection)
    end

    def submit
      @collection.submit!
      Event.log_event(Event.names[:collection_submitted], 'Collection', @collection.id, "Collection #{@collection.name} submitted at #{DateTime.now}", current_user.id)
      UserMailer.collection_notification(collection_id: @collection.id).deliver_later
      redirect_to admin_collection_path(@collection), notice: 'Collection has been submitted successfully.'
    end

    def publish
      @collection.publish!
      Event.log_event(Event.names[:collection_published], 'Collection', @collection.id, "Collection #{@collection.name} published at #{DateTime.now}", current_user.id)
      redirect_to admin_collection_path(@collection), notice: 'Collection has been published successfully.'
    end

    def copy
      ensure_collection_owner(collection: @collection)

      respond_to do |format|
        new_collection = @collection.duplicate!(new_user: current_user)

        if new_collection.valid?
          Event.log_event(Event.names[:collection_copied], 'Collection', @collection.id, "Collection #{@collection.name} copied at #{DateTime.now}", current_user.id)

          format.html { redirect_to admin_collection_path(new_collection), notice: 'Collection was successfully copied.' }
          format.json { render :show, status: :created, location: new_collection }
        else
          format.html { render :new }
          format.json { render json: new_collection.errors, status: :unprocessable_entity }
        end
      end
    end

    def create
      @collection = Collection.new(collection_params)

      @collection.user = current_user
      if @collection.save
        Event.log_event(Event.names[:collection_created], 'Collection', @collection.id, "Collection #{@collection.name} created at #{DateTime.now}", current_user.id)
        redirect_to admin_collection_path(@collection), notice: 'Collection was successfully created.'
      else
        render :new
      end
    end

    def update
      ensure_collection_owner(collection: @collection)

      if @collection.update(collection_params)
        Event.log_event(Event.names[:collection_updated], 'Collection', @collection.id, "Collection #{@collection.name} updated at #{DateTime.now}", current_user.id)
        redirect_to admin_collection_path(@collection), notice: 'Collection was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      ensure_collection_owner(collection: @collection)
      @collection.destroy
      Event.log_event(Event.names[:collection_deleted], 'Collection', @collection.id, "Collection #{@collection.name} deleted at #{DateTime.now}", current_user.id)
      redirect_to admin_collections_url, notice: 'Collection was successfully destroyed.'
    end

    def events
      @events = Event.where(object_type: 'Collection', object_id: @collection.id).order(:created_at)
    end

    def export_csv
      if performance_manager_permissions?
        @collections = Collection.all
      else
        @collections = current_user.collections
      end
      send_data @collections.to_csv, filename: "touchpoints-data-collections-#{Date.today}.csv"
    end

    def export_omb_cx_reporting_collections_csv
      ensure_performance_manager_permissions

      @omb_cx_reporting_collections = OmbCxReportingCollection.to_csv
      send_data @omb_cx_reporting_collections, filename: "touchpoints-omb-cx-reporting-data-collections-#{Date.today}.csv"
    end

    private

    def set_collection
      if performance_manager_permissions?
        @collection = Collection.find(params[:id])
      else
        @collection = current_user.collections.find(params[:id])
      end
    end

    def collection_params
      params.require(:collection).permit(
        :name,
        :start_date,
        :end_date,
        :organization_id,
        :service_provider_id,
        :year,
        :quarter,
        :user_id,
        :reflection,
        :integrity_hash,
        :aasm_state,
        :rating,
      )
    end
  end
end

app/controllers/api/v1/collections_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CollectionsController < ::ApiController
      def index
        respond_to do |format|
          format.json do
            if params[:all]
              render json: Collection.all.order(:id), each_serializer: CollectionSerializer
            else
              render json: Collection.published.order(:id), each_serializer: CollectionSerializer
            end
          end
        end
      end
    end
  end
end

app/views/admin/collections/edit.html.erb
<% content_for :navigation_title do %>
  Editing Data Collection
<% end %>

<p>
  <%= link_to admin_collection_path(@collection) do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Data Collection
  <% end %>
</p>

<%= render 'form', collection: @collection %>

<hr>

<p>
  <%= link_to admin_collection_path(@collection), method: :delete, data: { confirm: 'Are you sure?' }, class: "usa-button usa-button--secondary" do %>
    <i class="fa fa-trash"></i>
    Delete
  <% end %>

  <%= link_to copy_admin_collection_path(@collection), method: :post, class: "usa-button usa-button--outline float-right", data: { confirm: 'Are you sure?' } do %>
    <i class="fa fa-trash"></i>
    Copy this collection
  <% end %>
</p>

app/views/admin/collections/index.html.erb
<% content_for :navigation_title do %>
  Data Collections
  <%= link_to new_admin_collection_path, class: "usa-button usa-button-inverted float-right" do %>
    <i class="fa fa-pencil-alt"></i>
    New Data Collection
  <% end %>
<% end %>

<br>

<div
  class="usa-summary-box"
  role="region"
  aria-labelledby="summary-box-key-information">
  <div class="usa-summary-box__body">
    <h3 class="usa-summary-box__heading" id="summary-box-key-information">
      Managing Data Collections in Touchpoints
    </h3>
    <div class="usa-summary-box__text">
      <p>
        Data Collections are a common user experience in federal government.
        These Data Collections feature were created for
        1. staff who create Data Collections and
        2. staff who respond to Data Collections.
        Requesting updates for specific data, by creating a Data Collection, should be easy.
        Responding to Data Collections should also be easy.
        The lifecycle of the data should be transparent and valuable as well.
      </p>
      <p>
        Touchpoints currently facilitates 2
        Data Collections:
      </p>
      <ul class="usa-list">
        <li>
          OMB CX Data Collection (quarterly)
        </li>
        <li>
          GSA Website Data Collection (annually)
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="well">
  <div class="grid-row">
    <div class="grid-col-12">
      <div class="ui-filter">
        Filter by fiscal year and quarter
        <% if params[:year] || params[:quarter] %>
          <small>
            <%= link_to "View All Collections", admin_collections_path %>
          </small>
        <% end %>

        <div class="year" data-id="2022">
          <h4>
            2022
          </h4>
          <div>
            <%= link_to "Q1", admin_collections_path(quarter: 1, year: 2022), class: "usa-button #{params[:quarter] == "1" && params[:year] == "2022" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q2", admin_collections_path(quarter: 2, year: 2022), class: "usa-button #{params[:quarter] == "2" && params[:year] == "2022" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q3", admin_collections_path(quarter: 3, year: 2022), class: "usa-button #{params[:quarter] == "3" && params[:year] == "2022" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q4", admin_collections_path(quarter: 4, year: 2022), class: "usa-button #{params[:quarter] == "4" && params[:year] == "2022" ? nil : 'usa-button--outline'}" %>
          </div>
        </div>

        <div class="year" data-id="2021">
          <h4>
            2021
          </h4>
          <div>
            <%= link_to "Q1", admin_collections_path(quarter: 1, year: 2021), class: "usa-button #{params[:quarter] == "1" && params[:year] == "2021" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q2", admin_collections_path(quarter: 2, year: 2021), class: "usa-button #{params[:quarter] == "2" && params[:year] == "2021" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q3", admin_collections_path(quarter: 3, year: 2021), class: "usa-button #{params[:quarter] == "3" && params[:year] == "2021" ? nil : 'usa-button--outline'}" %>
            <%= link_to "Q4", admin_collections_path(quarter: 4, year: 2021), class: "usa-button #{params[:quarter] == "4" && params[:year] == "2021" ? nil : 'usa-button--outline'}" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

<table class="usa-table collections">
  <thead>
    <tr>
      <th data-sortable scope="col">Organization</th>
      <th data-sortable scope="col">Service Provider (HISP)</th>
      <th data-sortable scope="col">Collection name</th>
      <th data-sortable scope="col">Detail report count</th>
      <th data-sortable scope="col">Year</th>
      <th data-sortable scope="col">Quarter</th>
      <th data-sortable scope="col">Status</th>
      <th data-sortable scope="col">Rating</th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.organization.name %></td>
        <td><%= collection.service_provider ? collection.service_provider.name : "SPECIFY THIS COLLECTION'S SERVICE PROVIDER" %></td>
        <td><%= link_to collection.name, admin_collection_path(collection) %></td>
        <td><%= collection.omb_cx_reporting_collections.size %></td>
        <td><%= collection.year %></td>
        <td><%= collection.quarter %></td>
        <td>
          <%= render 'components/collection_status_tag', collection: collection %>
        </td>
        <td data-sort-value="<%= collection_rating_sort_values[collection.rating] %>">
          <%= collection_rating_label(rating: collection.rating) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if performance_manager_permissions? %>
  <p>
    <%= link_to "Download Collections as .csv", export_csv_admin_collections_path, class: "usa-button" %>
  </p>
  <p>
    <%= link_to "Download OMB CX Data Reporting Collections as .csv", export_omb_cx_reporting_collections_csv_admin_collections_path, class: "usa-button" %>
  </p>
<% end %>

<% if admin_permissions? %>
  <%= render 'admin/collections/hisps_csv_details' %>
  <%= render 'admin/components/performancegov/cx_summary_chart' %>
<% end %>

app/views/admin/collections/show.html.erb
<%= javascript_include_tag "chartjs-2.9.3.bundle.js" %>
<%= javascript_include_tag "performance-charts.js" %>

<% content_for :navigation_title do %>
  Data Collection
  <% if @collection.draft? || performance_manager_permissions? %>
    <%= link_to edit_admin_collection_path(@collection), class: "usa-button usa-button-inverted float-right" do %>
      <i class="fa fa-pencil-alt"></i>
      Edit
    <% end %>
  <% end %>
<% end %>

<p>
  <%= link_to admin_collections_path do %>
    <i class="fa fa-arrow-circle-left"></i>
    Back to Data Collections
  <% end %>
</p>

<h2>
  <%= @collection.name %>
</h2>

<% if !@collection.submitted? && !@collection.published? %>
<% elsif !@collection.published? %>
<% else %>
  <div class="usa-alert usa-alert--warning">
    <div class="usa-alert__body">
      <p class="usa-alert__text">
        This data collection has been published.
      </p>
    </div>
  </div>
  <br>
<% end %>

<p class="text-uppercase font-body-3xs">
  About this data collection
</p>
<div class="usa-alert">
  <div class="usa-alert__body">
    <p class="usa-alert__text">
      CX Customer Experience reporting is described in
      <a href="https://www.performance.gov/cx/assets/files/2022-OMB-Circular-A11-Section-280.pdf"
        target="_blank" rel="noopener">OMB Circular A-11, Section 280</a>.
    </p>
    <p class="usa-alert__text">
      Each quarter, OMB coordinates this data collection from all HISPs.
      This data will be summarized and reported on
      <a href="https://performance.gov/cx/" target="_blank" rel="noopener">performance.gov/cx</a>.
    </p>
  </div>
</div>

<div class="grid-row grid-gap-lg">
  <div class="tablet:grid-col-8 padding-top-2">
    <div class="text-uppercase font-body-3xs">
      General information
    </div>
    <div class="grid-row">
      <div class="grid-col-6">
        <p>
          <%= label_tag :organization, nil, class: "usa-label" %>
          <%= link_to @collection.organization.name, admin_organization_path(@collection.organization) %>
        </p>
        <p>
          <%= label_tag :service_provider, "Service Provider", class: "usa-label" %>
          <%= link_to  @collection.service_provider.name, admin_service_provider_path( @collection.service_provider) %>
        </p>
        <p>
          <%= label_tag :user, nil, class: "usa-label" %>
          <%= link_to_if performance_manager_permissions?, @collection.user.email, admin_user_path(@collection.user) %>
        </p>
      </div>
      <div class="grid-col-6">
        <p>
          <%= label_tag :quarter_year, "Quarter and Fiscal year", class: "usa-label" %>
          Q<%= @collection.quarter %>
          FY<%= @collection.year %>
        </p>

        <p>
          <%= label_tag :date_range, "Date range", class: "usa-label" %>
          <span><%= @collection.start_date %></span>
          to
          <br>
          <span><%= @collection.end_date %></span>
        </p>
      </div>
    </div>

    <div class="services border border-base-lighter padding-2 padding-top-0 padding-bottom-0 margin-top-3">
      <h2>
        Services
        <small>
          (<%= @collection.omb_cx_reporting_collections.size %>)
        </small>
      </h2>
      <div class="usa-alert">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            Add a Service detail reporting page for each touchpoint available within a HISP service.
          </p>
        </div>
      </div>
      <ul class="usa-list">
      <% @collection.omb_cx_reporting_collections.order(:service_provided, :channel).each do |cx_collection| %>
        <li>
          <%= link_to ("#{cx_collection.try(:service).try(:name)} - #{cx_collection.service_provided}"), admin_omb_cx_reporting_collection_path(cx_collection) %>
        </li>
      <% end %>
      </ul>
      <% if @collection.draft? %>
      <p>
        <%= link_to new_admin_omb_cx_reporting_collection_path(collection_id: @collection.id), class: "usa-button usa-button--outline" do %>
          <i class="fa fa-plus"></i>
          Add a Service to report on
        <% end %>
      </p>
      <% end %>
      <%= render 'components/performance_charts', collection: @collection if @collection.omb_cx_reporting_collections.present? %>
    </div>

    <div class="usa-prose margin-top-3">
      <strong>Reflection text</strong>
      <p>
        <% if @collection.reflection? %>
          <%= to_markdown(@collection.reflection) %>
        <% else %>
        <div class="usa-alert usa-alert--warning usa-alert--slim">
          <div class="usa-alert__body">
            <p class="usa-alert__text">
              <%= raw("Please add Reflection Text describing  #{link_to 'edit', edit_admin_collection_path(@collection)} this Reflection text prior to submitting.") %>
            </p>
          </div>
        </div>
        <% end %>
      </p>
    </div>
    <p hidden>
      <strong>Integrity hash</strong>
      <br>
      <%= @collection.integrity_hash || "not yet published" %>
    </p>

    <br>

  </div>
  <div class="grid-col-4 well">
    <br>
    <%= render 'components/step_indicator', collection: @collection %>
    <p>
      <%= label_tag :collection_status, nil, class: "usa-label" %>
      <br>
      <%= render 'components/collection_status_tag', collection: @collection %>
    </p>
    <p>
      <%= label_tag :rating, nil, class: "usa-label" %>
      <br>
      <% if @collection.rating.present? %>
      <%= collection_rating_label(rating: @collection.rating) %>
      <% else %>
      <div class="usa-alert">
        <div class="usa-alert__body">
          <p class="usa-alert__text">
            This Collection will receive a
            <a href="https://github.com/GSA/touchpoints/wiki/Data-Collection-Rating" class="usa-link" target="_blank" rel="noopener">rating</a>
            after
            Submission.
          </p>
        </div>
      </div>
      <% end %>
    </p>

    <p>
      <% if !@collection.submitted? && !@collection.published? %>
        <div class="usa-alert usa-alert--info usa-alert--slim">
          <div class="usa-alert__body">
            <p class="usa-alert__text">
              Submitting this Data Collection will send an email
              to <%= ENV.fetch("TOUCHPOINTS_ADMIN_EMAILS").split(',').to_sentence %>
              who will
              1. review the data, then
              2. contact you via email
              prior to publishing data on performance.gov.
            </p>
          </div>
        </div>
        <br>
        <%= link_to submit_admin_collection_path(@collection), class: "usa-button full-width", method: "post", data: { confirm: 'Are you sure?' } do %>
          Submit this Data Collection
        <% end %>
      <% elsif !@collection.published? && performance_manager_permissions? %>
        <%= link_to publish_admin_collection_path(@collection), class: "usa-button", method: "post" do %>
          Publish this Data Collection
        <% end %>
      <% end %>
    </p>
  </div>
</div>